name: Create release

on:
    push:
        tags:
            - 'v*.*.*'

jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            -
                name: Create release
                id: create_release
                uses: actions/create-release@v1
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                with:
                    tag_name: ${{ github.ref }}
                    release_name: Release ${{ github.ref }}
                    draft: false
                    prerelease: ${{ contains(github.ref, 'beta') || contains(github.ref, 'rc') }}

    docker:
        runs-on: ubuntu-latest
        env:
            SCHEME: lassus-tricinium-project
        steps:
            -
                uses: actions/checkout@v2
            -
                name: Build docker image
                run: docker build -t $SCHEME -f Dockerfile .
            -
                name: Push docker image to ghcr.io
                env:
                    TAG_NAME: ${{ github.ref }}
                run: |
                    TAG="ghcr.io/wolfgangdrescher/$SCHEME"
                    VERSION="${TAG_NAME//v/}"
                    docker tag $SCHEME $TAG:$VERSION
                    docker tag $SCHEME $TAG:latest
                    docker images $TAG
                    echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
                    docker push $TAG:$VERSION
                    docker push $TAG:latest

