name: Deploy to stage with custom verovio build

on:
    push:
        branches:
            - master
    workflow_dispatch: ~

jobs:
    deploy:
        runs-on: ubuntu-latest
        container:
            image: ghcr.io/wolfgangdrescher/verovio-humlib-docker-image:latest

        steps:
            -
                name: Configure SSH
                env:
                    HOST: ${{ secrets.HOST }}
                    USERNAME: ${{ secrets.USERNAME }}
                    SSH_KEY: ${{ secrets.SSH_KEY }}
                    PORT: ${{ secrets.PORT }}
                run: |
                    mkdir -p /root/.ssh/
                    echo "$SSH_KEY" > /root/.ssh/server.key
                    chmod 600 /root/.ssh/server.key
                    cat >> /root/.ssh/config <<END
                    Host server
                        HostName $HOST
                        User $USERNAME
                        Port $PORT
                        IdentityFile /root/.ssh/server.key
                        StrictHostKeyChecking no
                    END
            
            -
                name: Test SSH
                env:
                    HOST: ${{ secrets.HOST }}
                    USERNAME: ${{ secrets.USERNAME }}
                    SSH_KEY: ${{ secrets.SSH_KEY }}
                    PORT: ${{ secrets.PORT }}
                run: |
                    pwd
                    (cd && pwd)
                    (cd ~ && pwd)
                    cat ~/.ssh/config 2>/dev/null
                    cat /root/.ssh/config 2>/dev/null
                    mkdir dist
                    echo "<h1>Hello</h1>" > dist/index.html
                    echo "rsync 1:"
                    echo $SSH_KEY | rsync -rvzP -e 'ssh -i /dev/stdin -p $PORT' dist/ $USERNAME@$HOST:lassus.wolfgangdrescher.ch --delete
                    echo "rsync 2:"
                    echo $SSH_KEY | rsync -rvzP -e 'ssh -i /dev/stdin -p $PORT -o StrictHostKeyChecking=no' dist/ $USERNAME@$HOST:lassus.wolfgangdrescher.ch --delete
                    echo "rsync 3:"
                    rsync -e 'ssh -vvv' -azP dist/ server:lassus.wolfgangdrescher.ch --delete

            -
                name: Checkout
                uses: actions/checkout@v3
                with:
                    submodules: true

            -
                name: Setup node env
                uses: actions/setup-node@v3
                with:
                    node-version: 18

            -
                name: Cache node_modules
                uses: actions/cache@v3
                with:
                    path: ~/.npm
                    key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
                    restore-keys: |
                        ${{ runner.os }}-node-

            -
                name: Install dependencies
                run: npm ci

            -
                name: Build and analyze music with humdrum/humlib
                run: node scripts/cadences.mjs

            -
                name: Use custom verovio build
                run: |
                    npm remove verovio
                    cp -r /usr/local/verovio/emscripten/npm ./verovio
                    rm -rf ./verovio/node_modules
                    rm -rf ./verovio/src
                    rm ./verovio/package-lock.json
                    npm i ./verovio/

            -   
                name: Generate
                env:
                    BASE_URL: https://lassus.wolfgangdrescher.ch
                run: npm run generate

            -
                name: Deploy
                run: rsync -e 'ssh -vvv' -azP dist/ server:lassus.wolfgangdrescher.ch --delete
