name: Deploy to stage

on:
  push:
    branches:
        - master
  workflow_dispatch: ~

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Configure SSH
        env:
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          SSH_KEY: ${{ secrets.SSH_KEY }}
          PORT: ${{ secrets.PORT }}
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/server.key
          chmod 600 ~/.ssh/server.key
          cat >>~/.ssh/config <<END
          Host server
            HostName $HOST
            User $USERNAME
            Port $PORT
            IdentityFile ~/.ssh/server.key
            StrictHostKeyChecking no
          END

      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true


      - name: Setup node env
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci

      - name: Generate
        env:
          BASE_URL: https://lassus.wolfgangdrescher.ch
        run: npm run generate

      - name: Deploy
        run: rsync -azP dist/ server:lassus.wolfgangdrescher.ch --delete
